spring.application.name=hclinicas
server.port=8080
server.servlet.context-path=/api
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:hclinicas_db}
spring.datasource.username=${DB_USER:postgresadmin}
spring.datasource.password=${DB_PASSWORD:postgresadmin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public

spring.jackson.time-zone=America/Guayaquil

app.jwt.secret=5A7234753778217A25432A462D4A614E645267556B58703272357538782F413F
app.jwt.expiration=86400000
app.jwt.inactivity-timeout=1800000

app.cors.allowed-origins=https://klinixmed.org,https://www.klinixmed.org
#app.cors.allowed-origins=${ORIGINS_APP:http://localhost:4200}
logging.level.com.hclinicas=DEBUG
logging.level.org.springframework.security=INFO

app.qr.url-base=https://klinixmed.org/verificar
app.clinica.nombre=Consultorio Gineco-Obstetrico
app.clinica.especialista=Dra. Alexandra Le\u00f3n
app.clinica.especialidad=M\u00e9dico Especialista en Ginecologia y Obstetricia
app.clinica.direccion=Hospital San Juan - Riobamba, Ecuador
app.clinica.telefono=0999898989

spring.mail.host=mail.klinixmed.org
spring.mail.port=587
spring.mail.username=no-reply@klinixmed.org
spring.mail.password=TU_PASSWORD_CORREO
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false
app.mail.from=no-reply@klinixmed.org
app.mail.nombre-clinica=Consultorio Dra. Alexandra León